version: '3'
services:
  app:
    container_name: broker-service
    build:
      context: ./../broker-service 
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
       - 8080:8086
    deploy:
      mode: replicated
      replicas: 1